modLoader="lowcodefml"
loaderVersion="[43,)"
license="All Rights Reserved"
#issueTrackerURL="https://space.bilibili.com/321574895?spm_id_from=333.33.0.0"
[[mods]]
modId="cyan_ancient_city"
version="4.8.1"
displayName="青岭风格包"
#updateJSONURL="https://space.bilibili.com/321574895?spm_id_from=333.33.0.0" #optional
displayURL="B站：https://space.bilibili.com/321574895?spm_id_from=333.33.0.0"
logoFile="logo.png"
credits="感谢下载"
authors="IiI鱼老板IiI"
displayTest="IGNORE_SERVER_VERSION"
description='''模拟殖民地的中式风格包'''
[[dependencies.cyan_ancient_city]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cyan_ancient_city]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cyan_ancient_city]]
    modId="minecolonies"
    mandatory=true
    versionRange="[1.20.1-1.1.60-BETA,)"
    ordering="NONE"
    side="SERVER"

